name: simple_animated_button
description: This package offers a collection of ready-to-use, efficiently crafted, and elegantly designed animated buttons.
version: 0.0.9

homepage: https://github.com/NachiketGohil/simple_animated_button/blob/main/README.md
repository: https://github.com/NachiketGohil/simple_animated_button
license: BSD-3

maintainers:
  - name: Nachiket Gohil
    email: nachiketgohil185@gmail.com

topics:
  - animation
  - widget
  - button

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.1


flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic